### ISSUE TITLE
Add a landing page and site navigation

### ISSUE THREAD

**Issue by justwheel** [tillioss/tilli-docs#11]
There is [no landing page](https://tillioss.github.io/tilli-docs/) on the Tilli docs website. If someone navigates to the website, it appears like the site is an empty page. It is difficult to discover content; there is no menu navigation or search feature. The website appears to be under development.

Some kind of introduction to Tilli's overall work and open source efforts should go here. This is where a first impression can be made for someone who is discovering Tilli and the open source parts for the first time. This is a good place to call out attention to the most strategic and most important components to encourage engagement around those components.

![Screenshot of the current landing page on tillioss.github.io/tilli-docs/](https://user-images.githubusercontent.com/4721034/205386208-c7964a41-4d27-4517-8ad5-465874766d49.png "Screenshot of the current landing page on tillioss.github.io/tilli-docs/")

**Comment by Hannah31George** [comment]
We faced some issues trying to update this landing page. Instead, we have created a landing on our website: https://www.tillikids.com/opensource and linked the same everywhere.

**Comment by justwheel** [comment]
@Hannah31George I think there is a confusion, which we can clear up in today's scheduled call. But it is confusing to have two different sites with similar but different information. If you will not work on this site, then we need to close it down and migrate to the main website. But this also means we need to revisit UNICEF workplan requirements because this is noncompliant.

There is also information on the page linked above, like the project charter, which requires an account to view. But this content is also on the open source site.

It helps us at the Venture Fund to keep tabs on this issue. It would be great to keep it open until we resolve it.

**Comment by Briandsouza-17** [comment]
We have updated the landing page of the project charter to avoid confusion.
