### ISSUE TITLE
New doc: Identify the team working on the Open Source repositories and platforms

### ISSUE THREAD

**Issue by justwheel** [tillioss/tilli-docs#13]
One piece of useful documentation for an Open Source community to know is who is involved and what role they play in the project. From the outside, it can be hard to know who does what, or if I have a question, who is the right person to ask.

A new documentation page can introduce the team and put faces to names. It can document what each person's role is and offer a preferred contact method for someone to get in touch. This gives the project a more human touch and also makes it easier for someone to get help with Tilli by talking to a human.

**Comment by Hannah31George** [comment]
For now we have added a link to the team page that is in our website to all the repos under the Get in Touch section.

Reference below:

## Get in Touch 

Learn more about what we are doing at our official website [tillikids.com/opensource](www.tillikids.com/opensource) <br>For more technical information, visit our documentation website [tillioss.github.io](https://tillioss.github.io/docs/project-charter) or write to any of our team members at support@tillikids.org for any doubts or queries.
To know more about our [team members](https://www.tillikids.com/team)

**Comment by justwheel** [comment]
This looks good. We can work through the relationship of these two sites with each other in our call today.
