### ISSUE TITLE
Update the nodejs and yarn versions in pre requisites

### ISSUE THREAD

**Issue by anjula-sack** [tillioss/tilli-docs#37]
### What happened?

We need to update the nodejs and yarn versions in pre requisites in our docs. Use the following versions,

```
Node-js --version >= 20.0.0
Yarn --version >= 1.22.20
```

<img width="1158" alt="image" src="https://github.com/user-attachments/assets/1ccd6c94-18fe-482a-b781-b75c7bf7c120">

### Which page in the documentation did you face the issue?

Getting started (Contribution Guidelines)

### Priority

High Priority

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Disura-Randunu** [comment]
@anjula-sack shall I work on this?
